export const artPrompts = [
  "A sussy song is playing",
  "Redraws the same thing several times in a row",
  "Sings along with the song",
  "Forgets to save the project",
  "Skips 2 songs in a row",
  "Is lost in her unnamed layers",
  "Spends too long on one small part",
  "Compares her current work to a previous piece",
  "Mentions needing a reference image",
  "Accidentally draws on the wrong layer",
  "Spends more time selecting colors than drawing",
  "Mentions not being sure how to draw something",
  "Complains about Krita",
  "Gets excited about a small success or improvement",
  '"I have an idea"',
  "Asks chat for feedback",
  "Uses the symmetry tool",
  "Takes a break to think about the drawing",
];