export const genericPrompts = [
  "Tells a story about her work",
  "Puts a typo in the stream title",
  "Her dogs are barking",
  "Can't stop laughing",
  "Randomly curses in French",
  "Gets jumpscared by her phone",
  "Gets jumpscared by a stream alert",
  "Is mean to someone in chat",
  '"You\'re jealous"',
  "Says something sus",
  "The stream buffers",
  "Misreads a chat's message",
  "Goes to the bathroom",
  "Technical difficulties",
  "Has a goldfish memory",
  "Asks chat for help",
  "Doesn't get a joke",
  '"Brain is not braining"',
  "Obvious lie",
  "Randomly starts singing",
  '"I\'m stupid"',
  "Talks about her cat",
  "Starts eating or drinking",
  "Mentions how tired she is",
  "Checks something on her phone",
  "Changes stream settings mid-stream",
  "Forgets what she was talking about mid-sentence",
  "Struggles to pronounce a word",
  "Wonders if the sound volume is fine",
  "Mentions how cold or hot it is",
  "Talks about a game she’s excited to play in the future",
  "Says she needs to finish something after stream",
  "*Burps*",
  "*Sneezes*",
  "Talks about food or being hungry",
  "Mentions upcoming stream or future plans",
  "Missclicks",
  "Checks Discord",
  "Mentions her tea",
  "Mentions Warframe",
  "Pronounces a word in a very Frenchy way",
];