export const horrorGamesPrompts = [
  "Gets scared by a harmless NPC or object",
  "Stays crouched and refuses to move",
  "Is stuck on a puzzle",
  "Turns around repeatedly to check behind her",
  "Pauses the game to calm down",
  "Accidentally wastes a key item",
  "Loses track of the objective",
  "Gets lost in the same area repeatedly",
  "Doesn't notice an obvious clue",
  "Finds a safe room and doesn't want to leave",
  "Forgets a key mechanic or item",
  'Calls an enemy "ugly" or "creepy"',
  "Misses something important while panicking",
  "Finds comfort in a non-threatening object (like a plant or chair)",
  "Randomly laughs at her own fear",
  "Runs in the wrong direction during a chase",
  "Crouches to hide but gets caught immediately",
  "Uses an item by mistake",
  "Crouch-walks through an entire area out of fear",
  "Tries to brute force a puzzle instead of solving it",
  "Falls for an obvious trap or bait",
  "Ignores tutorial hints or on-screen prompts",
  '"I\'m scared"',
  "Insults an enemy",
  "Is paralyzed by fear",
  "Fails so close to the goal",
  "Skips a dialogue",
  "Gets jumpscared by a non-scary sound",
  "Complains about the game",
];