export const languageGuessrPrompts = [
    "Makes a terrible guess",
    "Uses an hint",
    "Uses all the hints",
    "Plays a full game without using any hints",
    "Spends a long time thinking about the answer",
    "Claims that's the last game but continues anyway",
    "Trusts a chatter's guess",
    "Struggles to find a place on the map",
    "Gets carried by chat",
    "Guesses right by sheer luck",
    "Guesses the right country but the wrong language",
    "Encounters an easy language",
    "\"I have no idea\"",
    "The answer gets spoiled by a hint",
    "Gets called out by the website for her bad score",
    "Gets a score of 200 or higher",
]