export const otherGamesPrompts = [
  "Gets jumpscared by the game",
  "Ragequits the game",
  "Is stuck on a puzzle",
  "Dies in a stupid way",
  "Loses track of the objective",
  "Gets lost in the same area repeatedly",
  "Doesn't notice an obvious clue",
  "Fails a quick-time event",
  "Forgets a key mechanic or control",
  "Has to pause because the chat is making her laugh",
  "Uses an item by mistake",
  "Gets distracted and dies while reading chat",
  "Blames the game for something that was her fault",
  "Struggles with a basic platforming section",
  "Fails to complete an easy task due to panic",
  "Misses a jump and falls to their death",
  "Accidentally attacks an NPC",
  "Tries to brute force a puzzle instead of solving it",
  "Accidentally wastes a key item",
  "Falls for an obvious trap or bait",
  "Ignores tutorial hints or on-screen prompts",
  "Runs out of ammo or resources at a critical moment",
  "Complains about a bug or glitch",
  "Gets really unlucky",
  "Does something risky and it works out by luck",
  "Accidentally clicks/skips through important dialogue",
  "Struggles to read a text/note",
  "Completes a mission/level",
  "Fails so close to the goal",
  "Skips a dialogue",
];