export const rhythmGamesPrompts = [
    "Fails a song",
    "Succeeds a song",
    "Sings along with the song",
    "Tries to read chat mid-song",
    "Beats her high score",
    "Is overwhelmed by the song speed",
    "Stays silent for at least 30 seconds",
    "Taps out of rhythm and loses a big combo",
    "Nails a perfect combo on a difficult section",
    "Experiments with different difficulty levels",
    "Restarts the song",
    "Succeeds the song in the highest difficulty",
    "Replays the same song after completing it",
    "Unlocks something",
    "Can't decide which song to play",
    "Starts playing a lengthy song",
    "Starts playing a short song",
    "Reaches 200 of combo",
    "Loses combo 10 times in a song",
    "Quits a song early",
    "Gets a bad score on a song",
    "Gets the best score possible on a song",
    "Misses a lot of notes in a very short amount of time",
    "Checks the leaderboard",
    "Mentions disliking/hating a song",
    "Mentions loving a song",
    "Gets more than 80% of accuracy",
    "Plays a song for the first time",
];