export const soulsLikePrompts = [
  "Falls in the void",
  "Dies from fall damage",
  "Beats a boss first try",
  "Dies 10 times in a row on the same boss",
  "Gets jumpscared by the game",
  "Dies of greediness",
  "Dies from an elevator accident",
  "Finds a bonfire/site of grace",
  "Is blind",
  "Doesn't know where to go",
  "Slams her desk",
  "Accidentally attacks an NPC",
  "Wastes healing items when not needed",
  "Runs past enemies to avoid fighting",
  "Dies trying to retrieve souls/XP",
  "Underestimates a weak-looking enemy",
  "Dies to environmental hazards (like fire or poison)",
  "Misses an obvious shortcut",
  "Backstabs an enemy successfully",
  "Dies to a trap (like hidden arrows or a boulder)",
  "Underestimates the range of an enemy's attack",
  "Spams dodge roll and dies anyway",
  "Dies immediately after healing",
  "Rolls off a cliff during a dodge",
  "Gets surprised by an enemy ambush",
  "Misses a dodge and gets hit by a huge attack",
  "Fails to dodge or block a simple attack",
  "Gets stuck in an infinite loop of dying and respawning in the same spot",
  "Complains about the game being unfair",
  "Reads chat while in a boss fight",
  "Insults an enemy",
  '"I love this game"',
  '"I\'m dead"',
  "*Does weird screams*",
  "Beats a boss",
  "Dies on a boss in less than 10s",
  "Equips another weapon",
  "Activates a lever or a mechanism",
  "Uses a summon",
  "Fails so close to the goal",
  "Runs out of healing",
  "Skips a dialogue",
];